server:
  http_listen_port: 9093
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://localhost:9092/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        host: ward_workstation
        agent: promtail
        __path__: /var/log/nginx/*.log
